### ISSUE TITLE
Image increases in size after zypper update

### ISSUE THREAD

**Issue by tgeek77** [SUSE/zypper-docker#130]
Commands used:
zypper-docker update slesapache:unpatched slesapache:latest

Dockerfile: (SUSE Internal)
https://gitlab.suse.de/jsevans/sles-images/tree/master/sles_apachetest

Result:
```
jsevans@lab:~/Git/sles-images/sles_apachetest> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
slesapache          latest              5cfc0e09bfd6        6 minutes ago       369MB
slesapache          unpatched           0a1ce90f671f        10 minutes ago      232MB
```

**Comment by parlt91** [comment]
The reason for the size increase is that zypper downloads the packages to `/var/cache/zypp` inside the container. This cache is not cleaned up afterwards. 
A possible fix for this would be the following:
Implement a function that executes `mktemp -d` in the container and returns a string with created dir.
Execute the zypper commands with the `-C, --cache-dir` flag and specify the output of `mktemp -d` as alternative cache dir. 
This causes the packages to be downloaded to the tmp dir.
Afterwards that directory can be removed.

This approach is to be preferred over the usage of `zypper clean`, since this way an already existing cache won't be touched.

**Comment by parlt91** [comment]
It seems that I was wrong about the reason for the size increase of the resulting image after `zypper docker up`. The cache is already being cleaned up with `zypper clean` after the update. 
The images increases in size because the changes made during the update are committed to a new image with `containerCommit(...)`. This creates a new layer (containing the changes) on top of the previous image. 
The size increase after the update is the size of the new layer that is being created during the process.

There is an option to `docker build --squash` which squashes all layers into one, but needs the docker daemon to run with experimental features enabled. It also has the downside that is squashes other already existing layers into the base image, which might not be desirable.

**Comment by vrothberg** [comment]
I suggest closing this bug. If a user wishes to avoid the size increase, `docker export` and `docker import` will achieve "squashing" the layers at the cost of losing the history. There is no other way around the issue as this is how layers work.
