### ISSUE TITLE
Allow updating of running containers

### ISSUE THREAD

**Issue by cyphar** [SUSE/zypper-docker#95]
This might lead to a slippery slope of people treating containers like VMs, but there might be legitimate reasons to do this (you are doing a rolling update, but it takes some time for each node to come up and you don't want all of the remaining nodes to be vulnerable).

We should probably discuss this (and make a proper proposal), but it's an interesting proposal IMO. Another cool thing we could do in that case is implement `zypper ps -s` for containers and then restart the container.

**Comment by mssola** [comment]
> This might lead to a slippery slope of people treating containers like VMs, but there might be legitimate reasons to do this (you are doing a rolling update, but it takes some time for each node to come up and you don't want all of the remaining nodes to be vulnerable).

We considered this when designing zypper-docker. The main problem being: what if in order to use the patched version of the library X you need to restart the entrypoint (e.g. updating openssl in a container which has Apache as the entrypoint) ? Updating containers is dangerous in this scenario because it would effectively kill them :D Therefore, we decided that it's up to the user to perform this task. If you want to have secure containers, update the image and re-schedule outdated containers. Orchestration solutions (or other external tools) should provide a way to do this. Thus, I'd say that it's a bit out of our scope.

The node problem is another thing entirely and it's something that we can't provide from the zypper-docker side. A possible solution for users is to use a tool that allows them to "drain" nodes (e.g. Nomad's `node-drain` command).

**Comment by cyphar** [comment]
One of the things I want to consider is making `zypper-docker` have support for different backends (like k8s and Nomad APIs). One more thing I should write an RFC about. ;)

**Comment by flavio** [comment]
I agree with @mssola, this could lead users to dangerous situations. I would close this feature if you don't mind.

**Comment by cyphar** [comment]
No problem. :D
